### ISSUE TITLE
error and used your api,help me 

### ISSUE THREAD

**Issue by BorgesGIT** [JessicaYeh/rom-exchange-openapi#1]
Hellloooo,
have nice day! I'm from Brasil! lol (dont look my writing english plzzzz, because my english is bad...) so...
I'm try a used your API, about my ideal , but, error....
I'd start in my localhost then user get "https://www.romexchange.com/api?item=shining%20stone&sort_server=global&slim=true&exact=true"
but erro about CORS....
then download and start on localhost:8080 user this link "http://localhost:8080/api?item=shining%20stone&sort_server=global&slim=true&exact=true" then 
erro again!

Can you send for my examples gets in localhost!

tks! nice WORKKKK

**Comment by marclfv** [comment]
Borges.

Seguinte.
Você baixou esse projeto aqui. 
Deu o "npm install"
Depois "npm start" 
e logo em seguida você simplesmente tentou usar "/api?........."

Se foi isso cara você esta tentando usar a API de forma errada.
Depois de dar o "npm start" vc tentou acessar o "http://localhost:8080/"
se não você vai ver que o que você baixou foi simplesmente uma cópia da documentação que ela disponibiliza nesse link.

https://jessicayeh.github.io/rom-exchange-openapi/

Posso esta falando muita merda também e estar sendo muito intrometido mas...

Para usar a API dela basta simplesmente que você realize uma requisição HTTP.Get para url dela...
"https://www.romexchange.com/api?........." passando os parâmetros que você deseja.

Geralmente erro de CORS é quando você esta tentando realizar uma requisição para uma url de um domínio externo para outro via browser. Para resolver isso ela la no servidor deveria configurar na aplicação o "Access-Control-Allow-Origin" para aceitar requisições de *(todos), porém, ela não irá fazer...

Então se você quer utilizar a API dela você deve implementar outra forma de realizar as requisições como por exemplo o NodeJS ou usando .NET Core ou outra forma.

Espero ter ajudado.

**Comment by BorgesGIT** [comment]
Marcio!
Niceeeeee!
Realmente estava fazendo errado! NOOB!

Então, o que eu estou tentando fazer vou explicar ver se você me da uma "LUZ" !
Eu estou tentando chamar  "https://www.romexchange.com/api" com seus devidos parâmetros!
porem esta dando de Cors..... isso rodando minha Pagina em localhost e chamando a dela direto de dentro do angular/TypeScript, só que realmente ela não vai ajudar o server dele somente por minha causa rsrs....

Mas então vamos ver se estou certo:
1-Devo Baixar a o projeto "https://github.com/JessicaYeh/rom-exchange-web", roda o mesmo localhost e ai sim usar os comando o link "http://localhost:8080/+api?+Paramentros", na minha pagina?

segue o comando que estou utilizando pra efetuar o mesmo:

> 

import { HttpClient } from "@angular/common/http";
import { Injectable } from "@angular/core";

//const API = "http://localhost:8080/";
const API = "https://www.romexchange.com/";

@Injectable({ providedIn: 'root' })
export class ItemService {
  
    constructor(private http: HttpClient) {}
        
    listFromName(itemName: string) {

           return this.http
            .get<Object[]>(API + 'api?item=shining%20stone&sort_server=global&slim=true&exact=true');
    }
}

**Comment by marclfv** [comment]
Borges então... isso você não poderá ter dentro do seu AngularJS.

Como eu disse, o problema de CORS acontece quando você esta realizando uma requisição de um site para outro site, ou seja, domínios diferentes.

Minha sugestões são duas...
criar uma aplicação NodeJS ou .Net Core para ser esse intermediário entre seu domínio e o domínio da romexchange

basicamente o diagrama seria mais ou menos assim:
________________          ________________________           ________________
| seu domínio  | ---> | NodeJS ou .Net Core | ----> | romexchange |
|_______________| <--- |________________________| <---- |________________|

Do jeito que você esta fazendo ele só funcionaria se na aplicação dela ela configurasse o "Access-Control-Allow-Origin" para aceitar as requisições de qualquer lugar.

 Até tem pessoas que dizendo que da para fazer um "gambiarra" para isso, uma especie de proxy
(https://medium.com/@gigioSouza/resolvendo-o-problema-do-cors-com-angular-2-e-o-angular-cli-7f7cb7aab3c2), nunca usei isso então não sei te dar maiores detalhes, mas minha dica é que NodeJS é tão fácil quando Angular.

**Comment by BorgesGIT** [comment]
@marclfv Man, Muitooooooo obrigado mesmo de verde pela sua ajuda!

mas já entendi a merda que fiz...

Estou chamando uma API de dentro de um front... vai dar ruim mesmo!

Então resolvi criar uma api net.core e de dentro dela efetuar a Request!
Resultado? foii lindo!

vlw mano!
